Remove unused argument and improve skin fetching code

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,43 +1,49 @@
 #!/bin/bash
-set -e
-#set -x
+set -e		# Abort upon error
+#set -x		# Print every command to stdout
 
 #######################################
 #	See README.me
-#
+#	Supports Wemail.no, Sol.dk and Mailia.no
+#		./deploy app.wemail.no
 #	Arguments:
-#		repo (string): repo name
+#		destination (string): RC root's dir name
 #	Returns:
 #		1 upon error
 #		0 upon success
 #######################################
 function main() {
-	local readonly USAGE="Usage: ./deploy repo destination"
-	declare -a repos=("Sol.dk-RC" "Wemail-RC")
+	local readonly USAGE="Usage: ./deploy destination"
 
-	if [ "${#}" -ne 2 ]; then
-		err "Error: two arguments are required, ${#} received"
+	if [ "${#}" -ne 1 ]; then
+		err "Error: one argument expected, ${#} received"
 		err "${USAGE}"
-		err "Available repo:"
-		printf '\t%s\n' "${repos[@]}"
 		return 1
 	fi
 
-	# In Bash, it's easy to check if an array contains an element
-	if [[ ! ${repos[*]} =~ (^|[[:space:]])"${1}"($|[[:space:]]) ]]; then
-		err "Error: invalid argument provided. Available repo:"
-		printf '\t%s\n' "${repos[@]}"
-		return 1
+	local readonly dest="${1}"
+
+	# Make sure we have a config file available
+	if [[ ! -f "config/${dest}/config.inc.php" ]]; then
+		err "Error: config file 'config/${dest}/config.inc.php' does not exist"
+		return 2
 	fi
 
-	local readonly dest="${2}"
-	
-	local readonly skin=$(cat "config/${dest}/config.inc.php" | grep "'skin'" | cut -d"'" -f4)
-	[[ -z "${skin}" ]] && [[ -f "config/${dest}/custom.inc.php" ]] && local readonly skin=$(cat "config/${dest}/custom.inc.php" | grep "'skin'" | cut -d"'" -f4)
+	# Fetch skin, either from 'config.inc.php' or from 'custom.inc.php'
+	local skin=""
+	for f in config custom; do
+		# Get skin from $f.inc.php
+		[[ -f "config/${dest}/${f}.inc.php" ]] && \ 
+			local readonly temp=$(cat "config/${dest}/${f}.inc.php" | grep "'skin'" | cut -d"'" -f4)
 
+		# If temp is not empty, use it
+		[[ ! -z "${temp}" ]] && skin="${temp}"
+	done
+
+	# If $skin is still empty, abort
 	if [[ -z "${skin}" ]]; then
-		err "Error: Unable to detect active skin"
-		return 1
+		err "Error: Unable to find skin in config"
+		return 3
 	fi
 
 	echo -e "UPDATING WEBMAIL: ${dest}\n"
